spring.jpa:
  properties.hibernate:
    multiTenancy: NONE
    tenant_identifier_resolver: org.ideakat.webapp.persistence.TestTenantIdentifierResolver
    globally_quoted_identifiers: false
    format_sql: true
  hibernate.ddl-auto: none
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: true

spring.datasource:
  url: jdbc:h2:mem:public;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS public
  driverClassName: org.h2.Driver
  username: sa
  password: password

spring.liquibase:
  enabled: true
  change-log: classpath:/liquibase/changelog/db.changelog-master.xml
  url: jdbc:h2:mem:public;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS public
  user: sa
  password: password
  default-schema: public

spring.test.database.replace: none